---
title: "Microsoft SQl Server Test"
output: html_document
---

```{r setup}
library(DBI)
library(odbc)
library(readxl)
library(readxl)
  library(writexl)
  library(plyr)
  library(dplyr)
  library(data.table)
  library(zoo)
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  library(shinyWidgets)
  library(htmlwidgets)
  library(lubridate)
  library(tcltk)
  library(tidyverse)
  library(plotly)
  library(knitr)
  library(kableExtra)
  library(leaflet)
  library(grid)
  library(gridExtra)
  library(eeptools)
  library(ggQC)
  #library(zipcode)
  library(utils)
  library(scales)
  library(chron)
  library(bupaR)
  library(shiny)
  library(DT)
  library(DiagrammeR)
  library(shinyalert)
  library(edeaR)
  library(processmapR)
  library(processmonitR)
  library(processanimateR)
  library(tidyr)
  library(lubridate)
  library(RColorBrewer)
  library(DiagrammeR)
  library(ggplot2)
  library(leaflet)
  library(readr)
  library(highcharter)
  library(ggforce) # for 'geom_arc_bar'
  library(packcircles) # for packed circle graph
  library(viridis)
  library(ggiraph)
  library(treemapify)
  library(treemap)
  library(broom)
  library(extrafont)
  library(tis) # for US holidays
  library(vroom)
  library(sjmisc)
  library(tools)
  library(here)
  library(shinyBS)
  library(shinyscreenshot)
  library(fasttime)
  library(shinycssloaders)
  library(feather)
  # library(zipcodeR)
  library(formattable)
  library(shinyjs)
  library(janitor)
  library(patchwork)

#  con_caboodle <- dbConnect(odbc(),
 #                 Driver = "SQLServer",
  #                Server = "SEPIBOJP016001",
   #               UID = "kweons01",
    #              PWD = "Pasword01#PasPasword01#Pas",
     #             Port = 1433)              
#print(con_caboodle)
#print("Caboodle was succesful")
```
```{r}
con_hh <- dbConnect(odbc(),
                Driver = "SQLServer",
               Server = "10.2.42.69",
              UID = "kweons01",
             PWD = "Pasword01#PasPasword01#Pas",
            Port = 1433)     
 print(con_hh)
 print("Hand hygiene was successful")
 
 test <- read_xlsx("/nfs/data/Applications/Ambulatory/master_amb_mapping.xlsx")
 print(test)
```
```{r}
scheduling_data_raw <- as.data.frame(readRDS("/nfs/data/Applications/Ambulatory/Data_Updated/historical_data.rds")) %>%
  filter(!is.na(Campus)) %>%
  filter(Campus %in% c("NETWORK","MSM","MSH-MSDFP","ONCOLOGY","MSW","MSBI","MSUS","MSH- AMBULATORY CARE","MSDD")) %>%
  filter(Appt.Status == "Arrived") %>%
  filter(Appt.DateYear >= as.Date("2022-01-01"), Appt.DateYear <= as.Date("2022-08-01")) 
 
 print(sort(unique(scheduling_data_raw$Appt.DateYear)))
```
